### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by rokity** [maxogden/torrent#43]
I don't know why from command line this command doesn't work.
It's sample.
require("torrent");
torret ciccia.torrent

It doesn't work.
This is the error :
SyntaxError: Unexpected identifier
    at Object.exports.createScript (vm.js:24:10)
    at REPLServer.defaultEval (repl.js:221:25)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)
    at REPLServer.Interface._ttyWrite (readline.js:826:14)

If you have more examples of this module , please post it.
Thanks

**Comment by LinusU** [comment]
It's complaining that `torret ciccia.torrent` isn't valid javascript, which it isn't.

Maybe you are trying to use this program from the command line?

```bash
npm install -g torrent
torrent ciccia.torrent
```
